module.exports = {
      apps: [
            {
                  name: 'nexo-agent',
                  script: 'node_modules/tsx/dist/cli.mjs',
                  args: '--env-file=.env src/index.ts',
                  instances: 1,
                  exec_mode: 'fork',
                  autorestart: true,
                  max_restarts: 10,
                  restart_delay: 3000,
                  min_uptime: '10s',
                  max_memory_restart: '300M',
                  time: true,
            },
            {
                  name: 'nexo-web',
                  script: 'node_modules/tsx/dist/cli.mjs',
                  args: '--env-file=.env src/web/server.ts',
                  instances: 1,
                  exec_mode: 'fork',
                  autorestart: true,
                  max_restarts: 10,
                  restart_delay: 3000,
                  min_uptime: '10s',
                  max_memory_restart: '150M',
                  time: true,
            },
            {
                  name: 'nexo-reminders',
                  script: 'node_modules/tsx/dist/cli.mjs',
                  args: '--env-file=.env src/reminders/index.ts',
                  instances: 1,
                  exec_mode: 'fork',
                  autorestart: true,
                  max_restarts: 10,
                  restart_delay: 3000,
                  min_uptime: '10s',
                  max_memory_restart: '150M',
                  time: true,
            },
      ],
};
